<?php

namespace App\Models;

use App\Enums\AutomationStatus;
use App\Enums\AutomationTrigger;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Automation extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'trigger_type',
        'status',
        'channel',
        'template_id',
        'whatsapp_template_id',
        'delay_minutes',
        'conditions',
    ];

    protected $casts = [
        'trigger_type' => AutomationTrigger::class,
        'status' => AutomationStatus::class,
        'delay_minutes' => 'integer',
        'conditions' => 'array',
    ];

    /**
     * The associated email template.
     */
    public function template(): BelongsTo
    {
        return $this->belongsTo(MarketingTemplate::class, 'template_id');
    }

    /**
     * The associated WhatsApp template.
     */
    public function whatsappTemplate(): BelongsTo
    {
        return $this->belongsTo(WhatsAppTemplate::class, 'whatsapp_template_id');
    }

    /**
     * Check if this automation dispatches via WhatsApp.
     */
    public function isWhatsApp(): bool
    {
        return $this->channel === 'whatsapp';
    }

    /**
     * Check if this automation dispatches via Email.
     */
    public function isEmail(): bool
    {
        return $this->channel === 'email' || empty($this->channel);
    }

    /**
     * Executions generated by this automation.
     */
    public function executions(): HasMany
    {
        return $this->hasMany(AutomationExecution::class, 'automation_id');
    }

    /**
     * Scope query to active automations.
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('status', AutomationStatus::ACTIVE->value);
    }

    /**
     * Scope query to specific trigger.
     */
    public function scopeTrigger(Builder $query, AutomationTrigger|string $trigger): Builder
    {
        $value = $trigger instanceof AutomationTrigger ? $trigger->value : $trigger;
        return $query->where('trigger_type', $value);
    }

    /**
     * Check if the automation is active.
     */
    public function isActive(): bool
    {
        return $this->status === AutomationStatus::ACTIVE;
    }
}
